name: animal_world
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+4

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  flutter_bloc: ^9.1.1
  talker_flutter: ^5.1.9
  go_router: ^17.0.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  talker_bloc_logger: ^5.1.9
  shared_preferences: ^2.5.4
  liquid_glass_renderer: ^0.2.0-dev.4
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
